# Generated by Django 5.0.6 on 2024-05-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('carts', models.ManyToManyField(related_name='products', to='apis.cart')),
            ],
        ),
    ]
